export const SET_CHECKINGS_BALANCE = "";

export const LOAD_ALL_TRANSACTIONS = "LOAD_ALL_TRANSACTIONS";
export const LOAD_ALL_CUSTOMERS = "LOAD_ALL_CUSTOMERS";
export const LOAD_ALL_ACCOUNTS = "LOAD_ALL_ACCOUNTS";
