export const SET_CHECKINGS_BALANCE = "";

export const LOAD_ALL_TRANSACTIONS = "LOAD_ALL_TRANSACTIONS";
export const LOAD_ALL_CUSTOMERS = "LOAD_ALL_CUSTOMERS";
export const LOAD_ALL_ACCOUNTS = "LOAD_ALL_ACCOUNTS";

export const LOAD_SINGLE_CUSTOMER = "LOAD_SINGLE_CUSTOMER";

export const UPDATE_LOG_IN_STATUS = "UPDATE_LOG_IN_STATUS";
